FROM mysql
MAINTAINER 211906110

ENV MYSQL_ALLOW_EMPTY_PASSWORD no
ENV MYSQL_ROOT_PASSWORD 123456
ENV MYSQL_DATABASE docker_mysql
ENV MYSQL_USER admin
ENV MYSQL_PASSWORD 123456

ENV WORK_PATH /home/mysql

COPY setup.sh /docker-entrypoint-initdb.d/setup.sh
COPY schema.sql $WORK_PATH/schema.sql

RUN chmod a+x /docker-entrypoint-initdb.d/setup.sh

WORKDIR $WORK_PATH
EXPOSE 110

